name: Deploy Frontend to GitHub Pages (Disabled - using deploy-pages.yml instead)

# Disabled to avoid conflicts with deploy-pages.yml
# on:
#   push:
#     branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        env:
          # Ensure Vite base is correct for repo pages; this is picked up by vite.config.ts
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: npm run build:frontend

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
