name: Deploy Limpopo Connect with Key Vault

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Must match your Azure Web App runtime

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build app (adjust if your build script is different)
      - name: Build
        run: npm run build

      # 5️⃣ Login to Azure using publish profile
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      # 6️⃣ Fetch DB secrets from Key Vault
      - name: Fetch DB settings from Key Vault
        id: kv
        run: |
          VAULT_NAME="limpopoconnect-kv-801"
          export DB_HOST="limpopoconnect-db.postgres.database.azure.com"
          export DB_NAME="postgres"
          export DB_USER="limpopoconnect_admin@limpopoconnect-db"
          export DB_PORT="5432"
          export DB_PASSWORD=$(az keyvault secret show --vault-name $VAULT_NAME --name azure-postgres-admin-password --query value -o tsv)

          # Make all DB vars available as GitHub Actions env
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "DB_USER=$DB_USER" >> $GITHUB_ENV
          echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

      # 7️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: limpoconnect-webapp
          package: .
          slot-name: production

      # 8️⃣ Confirm deployment
      - name: Confirm deployment
        run: |
          echo "Deployment complete!"
          az webapp show -g limpopoconnect-rg -n limpoconnect-webapp --query "{name:name, state:state, defaultHostName:defaultHostName}"
