name: Sync Azure Key Vault Secrets

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Key Vault Sync
        uses: mbmcmullen27/azure-secrets@v1.0
        with:
          keyvault: ${{ secrets.AZURE_KEYVAULT_NAME }}
          token: ${{ secrets.GH_PAT }}
